In [22]:
import pandas as pd

In [26]:
df = pd.read_csv("../data/raw/immigration_data/immigration_stats_census_subdivisions.csv")

C:\Users\jinxi\AppData\Local\Temp\ipykernel_579212\1914775247.py:1: DtypeWarning: Columns (8,10,12,14,16,18,20,22,24,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/raw/immigration_data/immigration_stats_census_subdivisions.csv")

In [24]:
df

,REF_DATE,GEO,DGUID,Age (8D),Gender (3),Place of birth (290),Coordinate,Immigrant status and period of immigration (11):Total - Immigrant status and period of immigration[1],Symbol,Immigrant status and period of immigration (11):Non-immigrants[2],...,Immigrant status and period of immigration (11):2001 to 2010[7],Symbol.6,Immigrant status and period of immigration (11):2011 to 2021[8],Symbol.7,Immigrant status and period of immigration (11):2011 to 2015[9],Symbol.8,Immigrant status and period of immigration (11):2016 to 2021[10],Symbol.9,Immigrant status and period of immigration (11):Non-permanent residents[11],Symbol.10
0,2021,"Division No. 1, Subd. V",2021A00051001101,Total - Age,Total - Gender,Total – Place of birth,4.1.1.1,45.0,NaN,45.0,...,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
1,2021,"Division No. 1, Subd. V",2021A00051001101,Total - Age,Total - Gender,Inside Canada,4.1.1.2,45.0,NaN,45.0,...,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
2,2021,"Division No. 1, Subd. V",2021A00051001101,Total - Age,Total - Gender,Newfoundland and Labrador,4.1.1.3,45.0,NaN,45.0,...,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
3,2021,"Division No. 1, Subd. V",2021A00051001101,Total - Age,Total - Gender,Prince Edward Island,4.1.1.4,0.0,NaN,0.0,...,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
4,2021,"Division No. 1, Subd. V",2021A00051001101,Total - Age,Total - Gender,Nova Scotia,4.1.1.5,0.0,NaN,0.0,...,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3560662,2021,Glooscap 35,2021A00051207027,25 to 54 years,Women+,Dominican Republic,537.5.3.43,0.0,...,0.0,...,0.0,...,0.0,...,0.0,...,0.0,...,0.0,...
3560663,2021,Glooscap 35,2021A00051207027,25 to 54 years,Women+,Grenada,537.5.3.44,0.0,...,0.0,...,0.0,...,0.0,...,0.0,...,0.0,...,0.0,...
3560664,2021,Glooscap 35,2021A00051207027,25 to 54 years,Women+,Guadeloupe,537.5.3.45,0.0,...,0.0,...,0.0,...,0.0,...,0.0,...,0.0,...,0.0,...
3560665,2021,Glooscap 35,2021A00051207027,25 to 54 years,Women+,Haiti,537.5.3.46,0.0,...,0.0,...,0.0,...,0.0,...,0.0,...,0.0,...,0.0,...
3560666,2021,Glooscap 35,2021A00051207027,25 to 54 years,Women+,Jamaica,537.5.3.47,0.0,...,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
df[df["GEO"]=="Vancouver"]

Empty DataFrame
Columns: [REF_DATE, GEO, DGUID, Age (8D), Gender (3), Place of birth (290), Coordinate, Immigrant status and period of immigration (11):Total - Immigrant status and period of immigration[1], Symbol, Immigrant status and period of immigration (11):Non-immigrants[2], Symbol.1, Immigrant status and period of immigration (11):Immigrants[3], Symbol.2, Immigrant status and period of immigration (11):Before 1980[4], Symbol.3, Immigrant status and period of immigration (11):1980 to 1990[5], Symbol.4, Immigrant status and period of immigration (11):1991 to 2000[6], Symbol.5, Immigrant status and period of immigration (11):2001 to 2010[7], Symbol.6, Immigrant status and period of immigration (11):2011 to 2021[8], Symbol.7, Immigrant status and period of immigration (11):2011 to 2015[9], Symbol.8, Immigrant status and period of immigration (11):2016 to 2021[10], Symbol.9, Immigrant status and period of immigration (11):Non-permanent residents[11], Symbol.10]
Index: []

[0 rows x 29 columns]

In [8]:
df = df[df['Immigrant status and period of immigration (11):Total - Immigrant status and period of immigration[1]']!=0]

In [11]:
df = df[~df['Immigrant status and period of immigration (11):Total - Immigrant status and period of immigration[1]'].isna()]

In [12]:
df

,REF_DATE,GEO,DGUID,Age (8D),Gender (3),Place of birth (290),Coordinate,Immigrant status and period of immigration (11):Total - Immigrant status and period of immigration[1],Symbol,Immigrant status and period of immigration (11):Non-immigrants[2],...,Immigrant status and period of immigration (11):2001 to 2010[7],Symbol.6,Immigrant status and period of immigration (11):2011 to 2021[8],Symbol.7,Immigrant status and period of immigration (11):2011 to 2015[9],Symbol.8,Immigrant status and period of immigration (11):2016 to 2021[10],Symbol.9,Immigrant status and period of immigration (11):Non-permanent residents[11],Symbol.10
0,2021,Elkford,2021A00055901003,Total - Age,Total - Gender,Total – Place of birth,4570.1.1.1,2745.0,NaN,2535.0,...,10.0,NaN,90.0,NaN,70.0,NaN,20.0,NaN,10.0,NaN
1,2021,Elkford,2021A00055901003,Total - Age,Total - Gender,Inside Canada,4570.1.1.2,2525.0,NaN,2525.0,...,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
2,2021,Elkford,2021A00055901003,Total - Age,Total - Gender,Newfoundland and Labrador,4570.1.1.3,75.0,NaN,75.0,...,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
4,2021,Elkford,2021A00055901003,Total - Age,Total - Gender,Nova Scotia,4570.1.1.5,50.0,NaN,50.0,...,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
5,2021,Elkford,2021A00055901003,Total - Age,Total - Gender,New Brunswick,4570.1.1.6,30.0,NaN,30.0,...,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5198840,2021,Northern Rockies,2021A00055959007,65 to 74 years,Women+,Alberta,5344.8.3.11,20.0,NaN,20.0,...,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
5198841,2021,Northern Rockies,2021A00055959007,65 to 74 years,Women+,British Columbia,5344.8.3.12,75.0,NaN,75.0,...,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
5198845,2021,Northern Rockies,2021A00055959007,65 to 74 years,Women+,Outside Canada,5344.8.3.16,15.0,NaN,0.0,...,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
5198906,2021,Northern Rockies,2021A00055959007,65 to 74 years,Women+,Europe,5344.8.3.77,15.0,NaN,0.0,...,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
5198931,2021,Northern Rockies,2021A00055959007,65 to 74 years,Women+,Northern Europe,5344.8.3.102,15.0,NaN,0.0,...,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN

In [ ]:
df.to_parquet("../data/processed/immigration_data/immigration_stats_census_subdivisions.parquet", index=False)

# Use this if the csv is too large

In [27]:
def classify_birthplace(place):
    if place == "Total – Place of birth":
        return "Total"
    elif place == "Inside Canada":
        return "Inside Canada"
    elif place == "Outside Canada":
        return "Outside Canada"
    elif place in [
        "Newfoundland and Labrador", "Prince Edward Island", "Nova Scotia", "New Brunswick",
        "Quebec", "Ontario", "Manitoba", "Saskatchewan", "Alberta", "British Columbia",
        "Yukon", "Northwest Territories", "Nunavut"
    ]:
        return "Province"
    elif place in [
        "Americas", "Europe", "Africa", "Asia", "Oceania"
    ]:
        return "Continent"
    elif place in [
        "Northern Africa", "Western Africa", "Eastern Africa", "Middle Africa", "Southern Africa",
        "Eastern Asia", "Southeast Asia", "Southern Asia", "Western Asia", "Central Asia",
        "Western Europe", "Northern Europe", "Eastern Europe", "Southern Europe",
        "North America", "Central America", "Caribbean and Bermuda", "South America",
        "West Central Asia and the Middle East",
        "Central Africa", "Southern Africa", "Eastern Africa", "Northern Africa", "Western Africa",
        "Australia and New Zealand", "Melanesia", "Micronesia", "Polynesia"
    ]:
        return "Region"
    elif place in ["Other"]:
        return "Other"
    else:
        return "Country"

In [28]:
pruid_to_province = {
    '10': 'Newfoundland and Labrador',
    '11': 'Prince Edward Island',
    '12': 'Nova Scotia',
    '13': 'New Brunswick',
    '24': 'Quebec',
    '35': 'Ontario',
    '46': 'Manitoba',
    '47': 'Saskatchewan',
    '48': 'Alberta',
    '59': 'British Columbia',
    '60': 'Yukon',
    '61': 'Northwest Territories',
    '62': 'Nunavut'
}

def map_province(dguid):
    csduid = dguid[9:]  # Extract the geographic unique identifier (CSDUID)
    pruid = csduid[:2]  # Extract the first 2 digits (PRUID)
    return pruid_to_province.get(pruid, 'Unknown')

In [29]:
import pandas as pd

input_csv = "../data/raw/immigration_data/immigration_stats_census_subdivisions.csv"
output_parquet = "../data/processed/immigration_data/immigration_stats_census_subdivisions.parquet"
target_col = "Immigrant status and period of immigration (11):Total - Immigrant status and period of immigration[1]"

chunksize = 100_000
filtered_chunks = []

for chunk in pd.read_csv(input_csv, chunksize=chunksize):
    chunk[target_col] = pd.to_numeric(chunk[target_col], errors='coerce')
    filtered = chunk[(chunk[target_col] != 0) & (~chunk[target_col].isna())]
    filtered["Type"] = filtered["Place of birth (290)"].apply(classify_birthplace)
    filtered['Province'] = filtered['DGUID'].apply(map_province)
    filtered_chunks.append(filtered)

df = pd.concat(filtered_chunks, ignore_index=True)
df.to_parquet(output_parquet, index=False)

C:\Users\jinxi\AppData\Local\Temp\ipykernel_579212\1700243296.py:10: DtypeWarning: Columns (8,10,12,14,16,18,20,22,24,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(input_csv, chunksize=chunksize):
C:\Users\jinxi\AppData\Local\Temp\ipykernel_579212\1700243296.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered["Type"] = filtered["Place of birth (290)"].apply(classify_birthplace)
C:\Users\jinxi\AppData\Local\Temp\ipykernel_579212\1700243296.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered['Province'] = filtered['DGUID'].apply(map_province)
C:\Users\jinxi\AppData\Local\Temp\ipykernel_579212\1700243296.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered["Type"] = filtered["Place of birth (290)"].apply(classify_birthplace)
C:\Users\jinxi\AppData\Local\Temp\ipykernel_579212\1700243296.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered['Province'] = filtered['DGUID'].apply(map_province)
C:\Users\jinxi\AppData\Local\Temp\ipykernel_579212\1700243296.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered["Type"] = filtered["Place of birth (290)"].apply(classify_birthplace)
C:\Users\jinxi\AppData\Local\Temp\ipykernel_579212\1700243296.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered['Province'] = filtered['DGUID'].apply(map_province)
C:\Users\jinxi\AppData\Local\Temp\ipykernel_579212\1700243296.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered["Type"] = filtered["Place of birth (290)"].apply(classify_birthplace)
C:\Users\jinxi\AppData\Local\Temp\ipykernel_579212\1700243296.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered['Province'] = filtered['DGUID'].apply(map_province)
C:\Users\jinxi\AppData\Local\Temp\ipykernel_579212\1700243296.py:10: DtypeWarning: Columns (8,10,12,14,16,18,20,22,24,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(input_csv, chunksize=chunksize):
C:\Users\jinxi\AppData\Local\Temp\ipykernel_579212\1700243296.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered["Type"] = filtered["Place of birth (290)"].apply(classify_birthplace)
C:\Users\jinxi\AppData\Local\Temp\ipykernel_579212\1700243296.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered['Province'] = filtered['DGUID'].apply(map_province)
C:\Users\jinxi\AppData\Local\Temp\ipykernel_579212\1700243296.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered["Type"] = filtered["Place of birth (290)"].apply(classify_birthplace)
C:\Users\jinxi\AppData\Local\Temp\ipykernel_579212\1700243296.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered['Province'] = filtered['DGUID'].apply(map_province)
C:\Users\jinxi\AppData\Local\Temp\ipykernel_579212\1700243296.py:10: DtypeWarning: Columns (8,10,12,14,16,18,20,22,24,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(input_csv, chunksize=chunksize):
C:\Users\jinxi\AppData\Local\Temp\ipykernel_579212\1700243296.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered["Type"] = filtered["Place of birth (290)"].apply(classify_birthplace)
C:\Users\jinxi\AppData\Local\Temp\ipykernel_579212\1700243296.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered['Province'] = filtered['DGUID'].apply(map_province)
C:\Users\jinxi\AppData\Local\Temp\ipykernel_579212\1700243296.py:10: DtypeWarning: Columns (8,10,12,14,16,18,20,22,24,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(input_csv, chunksize=chunksize):
C:\Users\jinxi\AppData\Local\Temp\ipykernel_579212\1700243296.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered["Type"] = filtered["Place of birth (290)"].apply(classify_birthplace)
C:\Users\jinxi\AppData\Local\Temp\ipykernel_579212\1700243296.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered['Province'] = filtered['DGUID'].apply(map_province)
C:\Users\jinxi\AppData\Local\Temp\ipykernel_579212\1700243296.py:10: DtypeWarning: Columns (8,10,12,14,16,18,20,22,24,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(input_csv, chunksize=chunksize):
C:\Users\jinxi\AppData\Local\Temp\ipykernel_579212\1700243296.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered["Type"] = filtered["Place of birth (290)"].apply(classify_birthplace)
C:\Users\jinxi\AppData\Local\Temp\ipykernel_579212\1700243296.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered['Province'] = filtered['DGUID'].apply(map_province)
C:\Users\jinxi\AppData\Local\Temp\ipykernel_579212\1700243296.py:10: DtypeWarning: Columns (8,10,12,14,16,18,20,22,24,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(input_csv, chunksize=chunksize):
C:\Users\jinxi\AppData\Local\Temp\ipykernel_579212\1700243296.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered["Type"] = filtered["Place of birth (290)"].apply(classify_birthplace)
C:\Users\jinxi\AppData\Local\Temp\ipykernel_579212\1700243296.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered['Province'] = filtered['DGUID'].apply(map_province)
C:\Users\jinxi\AppData\Local\Temp\ipykernel_579212\1700243296.py:10: DtypeWarning: Columns (8,10,12,14,16,18,20,22,24,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(input_csv, chunksize=chunksize):
C:\Users\jinxi\AppData\Local\Temp\ipykernel_579212\1700243296.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered["Type"] = filtered["Place of birth (290)"].apply(classify_birthplace)
C:\Users\jinxi\AppData\Local\Temp\ipykernel_579212\1700243296.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered['Province'] = filtered['DGUID'].apply(map_province)
C:\Users\jinxi\AppData\Local\Temp\ipykernel_579212\1700243296.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered["Type"] = filtered["Place of birth (290)"].apply(classify_birthplace)
C:\Users\jinxi\AppData\Local\Temp\ipykernel_579212\1700243296.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered['Province'] = filtered['DGUID'].apply(map_province)
C:\Users\jinxi\AppData\Local\Temp\ipykernel_579212\1700243296.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered["Type"] = filtered["Place of birth (290)"].apply(classify_birthplace)
C:\Users\jinxi\AppData\Local\Temp\ipykernel_579212\1700243296.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered['Province'] = filtered['DGUID'].apply(map_province)
C:\Users\jinxi\AppData\Local\Temp\ipykernel_579212\1700243296.py:10: DtypeWarning: Columns (8,10,12,14,16,18,20,22,24,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(input_csv, chunksize=chunksize):
C:\Users\jinxi\AppData\Local\Temp\ipykernel_579212\1700243296.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered["Type"] = filtered["Place of birth (290)"].apply(classify_birthplace)
C:\Users\jinxi\AppData\Local\Temp\ipykernel_579212\1700243296.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered['Province'] = filtered['DGUID'].apply(map_province)
C:\Users\jinxi\AppData\Local\Temp\ipykernel_579212\1700243296.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered["Type"] = filtered["Place of birth (290)"].apply(classify_birthplace)
C:\Users\jinxi\AppData\Local\Temp\ipykernel_579212\1700243296.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered['Province'] = filtered['DGUID'].apply(map_province)
C:\Users\jinxi\AppData\Local\Temp\ipykernel_579212\1700243296.py:10: DtypeWarning: Columns (8,10,12,14,16,18,20,22,24,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(input_csv, chunksize=chunksize):
C:\Users\jinxi\AppData\Local\Temp\ipykernel_579212\1700243296.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered["Type"] = filtered["Place of birth (290)"].apply(classify_birthplace)
C:\Users\jinxi\AppData\Local\Temp\ipykernel_579212\1700243296.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered['Province'] = filtered['DGUID'].apply(map_province)
C:\Users\jinxi\AppData\Local\Temp\ipykernel_579212\1700243296.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered["Type"] = filtered["Place of birth (290)"].apply(classify_birthplace)
C:\Users\jinxi\AppData\Local\Temp\ipykernel_579212\1700243296.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered['Province'] = filtered['DGUID'].apply(map_province)
C:\Users\jinxi\AppData\Local\Temp\ipykernel_579212\1700243296.py:10: DtypeWarning: Columns (8,10,12,14,16,18,20,22,24,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(input_csv, chunksize=chunksize):
C:\Users\jinxi\AppData\Local\Temp\ipykernel_579212\1700243296.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered["Type"] = filtered["Place of birth (290)"].apply(classify_birthplace)
C:\Users\jinxi\AppData\Local\Temp\ipykernel_579212\1700243296.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered['Province'] = filtered['DGUID'].apply(map_province)
C:\Users\jinxi\AppData\Local\Temp\ipykernel_579212\1700243296.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered["Type"] = filtered["Place of birth (290)"].apply(classify_birthplace)
C:\Users\jinxi\AppData\Local\Temp\ipykernel_579212\1700243296.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered['Province'] = filtered['DGUID'].apply(map_province)
C:\Users\jinxi\AppData\Local\Temp\ipykernel_579212\1700243296.py:10: DtypeWarning: Columns (8,10,12,14,16,18,20,22,24,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(input_csv, chunksize=chunksize):
C:\Users\jinxi\AppData\Local\Temp\ipykernel_579212\1700243296.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered["Type"] = filtered["Place of birth (290)"].apply(classify_birthplace)
C:\Users\jinxi\AppData\Local\Temp\ipykernel_579212\1700243296.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered['Province'] = filtered['DGUID'].apply(map_province)

In [17]:
df[df["GEO"]=="Vancouver"]

Empty DataFrame
Columns: [REF_DATE, GEO, DGUID, Age (8D), Gender (3), Place of birth (290), Coordinate, Immigrant status and period of immigration (11):Total - Immigrant status and period of immigration[1], Symbol, Immigrant status and period of immigration (11):Non-immigrants[2], Symbol.1, Immigrant status and period of immigration (11):Immigrants[3], Symbol.2, Immigrant status and period of immigration (11):Before 1980[4], Symbol.3, Immigrant status and period of immigration (11):1980 to 1990[5], Symbol.4, Immigrant status and period of immigration (11):1991 to 2000[6], Symbol.5, Immigrant status and period of immigration (11):2001 to 2010[7], Symbol.6, Immigrant status and period of immigration (11):2011 to 2021[8], Symbol.7, Immigrant status and period of immigration (11):2011 to 2015[9], Symbol.8, Immigrant status and period of immigration (11):2016 to 2021[10], Symbol.9, Immigrant status and period of immigration (11):Non-permanent residents[11], Symbol.10, Type, Province]
Index: []

[0 rows x 31 columns]